import 'package:xilancer/business_logic/core/utils/const_strings.dart';

var translateStrings = {
  ConstString.createAnAccount: ConstString.createAnAccount,
  ConstString.plzCheckInternet: ConstString.plzCheckInternet,
  ConstString.chooseArole: ConstString.chooseArole,
  ConstString.chooseRoleToSignup: ConstString.chooseRoleToSignup,
  ConstString.joinAsAfreelancer: ConstString.joinAsAfreelancer,
  ConstString.continueTxt: ConstString.continueTxt,
  ConstString.firstName: ConstString.firstName,
  ConstString.lastName: ConstString.lastName,
  ConstString.email: ConstString.email,
  ConstString.phone: ConstString.phone,
  ConstString.password: ConstString.password,
  ConstString.createAccount: ConstString.createAccount,
  ConstString.dontHaveAccount: ConstString.dontHaveAccount,
  ConstString.login: ConstString.login,
  ConstString.loginWithGoogle: ConstString.loginWithGoogle,
  ConstString.loginWithFb: ConstString.loginWithFb,
  ConstString.plzEnterFirstName: ConstString.plzEnterFirstName,
  ConstString.plzEnterLastName: ConstString.plzEnterLastName,
  ConstString.plzEnterEmail: ConstString.plzEnterEmail,
  ConstString.plzEnterPass: ConstString.plzEnterPass,
  ConstString.alreadyHaveAnAccount: ConstString.alreadyHaveAnAccount,
  ConstString.signUp: ConstString.signUp,
  ConstString.setupYourAccount: ConstString.setupYourAccount,
  ConstString.whatProfDescYou: ConstString.whatProfDescYou,
  ConstString.exFrontendDev: ConstString.exFrontendDev,
  ConstString.provideIntro: ConstString.provideIntro,
  ConstString.exIamProDev: ConstString.exIamProDev,
  ConstString.back: ConstString.back,
};
